services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mns_db
    volumes:
      - ./mysql_data_new:/var/lib/mysql
    networks:
      - twotier
    ports:
      - "3306:3306"

  flaskapp:
    build:
      context: .
    container_name: flaskapp
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DB: mns_db
    networks:
      - twotier
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    restart: always


volumes:
  mysql_data_new:

networks:
  twotier:


